# Generated by Django 4.0 on 2021-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="int_end",
            field=models.IntegerField(default=100000000, verbose_name="To"),
        ),
        migrations.AddField(
            model_name="column",
            name="int_start",
            field=models.IntegerField(default=0, verbose_name="From"),
        ),
        migrations.AddField(
            model_name="column",
            name="txt_sentences_quantity",
            field=models.IntegerField(default=3, verbose_name="Sentences"),
        ),
        migrations.AlterField(
            model_name="column",
            name="kind",
            field=models.CharField(
                choices=[
                    ("Full Name", "Full Name"),
                    ("Job", "Job"),
                    ("Email", "Email"),
                    ("Domain name", "Domain name"),
                    ("Phone number", "Phone number"),
                    ("Company name", "Company name"),
                    ("Text", "Text"),
                    ("Integer", "Integer"),
                    ("Address", "Address"),
                    ("Date", "Date"),
                ],
                default="Full Name",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="character",
            field=models.CharField(
                choices=[('"', 'Double-quote (")'), ("'", "Singe-quote (')")],
                default='"',
                max_length=5,
                verbose_name="String character",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="separator",
            field=models.CharField(
                choices=[(".", "Point (.)"), (",", "Coma (,)")],
                default=".",
                max_length=5,
                verbose_name="Column separator",
            ),
        ),
    ]
