# Generated by Django 4.0 on 2021-12-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="scheme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="column",
                to="base.scheme",
                verbose_name="Scheme",
            ),
        ),
    ]
