# Generated by Django 4.0 on 2021-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_column_int_end_column_int_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="int_end",
            field=models.IntegerField(default=1000000, verbose_name="To"),
        ),
    ]
